version: '3'
services:
  api:
    image: adeo/api-Bortoluzzapi
    build:
      context: .
      dockerfile: install/Dockerfile-api
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 1
  redis:
    image: redis:4
    command: ["redis-server", "--port", "6379"]
    restart: always